let handler = async(m, { conn }) => {
  conn.reply(m.chat, `buat kalian yg ingin belajar bahasa jepang,☺️semoga bermanfaat,🙏‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎

• baka yarou ! = dasar bego!
• senpai = senior
• kouhai = junior
• hidoi = jahat
• dousta? = kenapa?, ada apa?
• nani!! = apa!!
• zutto = kalau saja, selalu
• kirei = indah
• kawaii = cantik, imut
• yaksoku = janji
• kedo/demo = tapi
• warui/gomen = maaf
• sumimasen = permisi, maaf
• omedetou, ne = selamat ya
• dame = jangan, tidak
• sugoi! = hebat, keren
• daijoubu desu = saya tidak apa apa / saya baik baik saja
• hanabi = kembang api
• tadaima = aku pulang
• okaerinasai = selamat pulang
• ja, mata/ mata ne = sampai jumpa
• ittekimasu = aku berangkat
•itterasshai = hati hati di jalan
• ohayou = selamat pagi
• konnichiwa = selamat siang
• konbanwa = selamat malam
• oyasumi = selamat tidur
• moshi-moshi = halo
• zannen desu = sayang sekali
• irasshaimase = selamat datang
• onegai = tolong
• yoroshiku onegaishimasu = mohon bimbingannya/bantuannya
• doumo/arigatou = terima kasih
• iya = hai
• iie = tidak
• ittadakimasu = selamat makan
• nandemonai = bukan apa apa
• nanda korewa? = apa ini?
• dare desu ka? = siapa ini?
• wakatta = oke, ngerti.
• sou ne .. = begitulah, mungkin
• masaka.... = nggak mungkin..... (ah masa .....)
• naru hodo = oh gitu
•yokatta... = syukurlaah....
• hontou ni?/souka? = bener gitu?
• kimi wa boku no mono = kamu milikkuuu
• ki o tsukete ne = hati-hati yah~
• onaka ga suita = aku laperr
• itadakimassuuu = selamat makaaannn
• ii yume wo mite ne = mimpi indah yah,
• yatta ! = horee!
• kawaisou ni... = kasian...
• chotto matte ! = tunggu bentar!
• uso = bohong
• uso tsuki ! = tukang bohong!
• uso jyanai! = jangan bohong!
• nan da yo!? = ape lu !?
• damareeee! = dieeemmm!
• omae wa kankei nai darou.. ! = bukan urusanmu..!
• mata ne / mata yo ~ = sampe jumpa~
• oyasumi = met istirahat (met tidur)
• jibun no sei da = salah sendiri
• hitomebore datta no yo... = cinta pada pandangan pertama...............(cikiciew)
• doki-doki shichatta yo... = aku jadi deg-degan nih...
• suki da .. = aku suka kamu
• kareshi ga iru no ? = udah punya pacar?
• bukkoroshite yaruuu! = akan kubunuh kauuu! (bisanya diucapkan kalau lagi pada berantem)
• kusso !! = ta* !! / br*ngs*k !! (diucapkan oleh kaum laki-laki dalam anime kalau lagi kesel)
• kimi no katte da! = terserah kamu dah!
• 39 (baca : sankyuu ) = makasih
• ittekimasu = aku berangkat
• itterasshai = silahkan berangkaat (jawaban dari ittekimasu) (shinchan selalu kebalik berkata "itterasshai" kalau mau pergi keluar rumah -_- ) • kami nomi zo shiru sekai = dunia hanya tuhan yang mengetahui..(ini sih judul anime... hehe)
• aitai naa = kangen nih... >.<
• ima made arigatou.. = makasih untuk segalanya... (kalau mau putus biasnaya suka ngomong gini deh)
• do iu koto? = maksudnya apa?
• chigau yo ! = salah kok!
• dame da yo! = ga boleh! (jangan!) • kocchi kocchi = sini sini
• naicha ikenai yo! = jangan nangis!
• anata dare na no? = kamu siapa?
• ii yo .. = boleh..~
• boku, kimi no koto suki da yo = aku suka kamu....(loh)
• dou sureba ii? = apa yang harus aku lakukan?
• yamete yo! = berhentii!
• bochi-bochi ganbari yaa! = (entah apa artinyah, namun biasanya ungkapan ini untuk memberikan semangat kayak "ganbatte")
• anata ga itooshii = aku sayang kamyu
• aite ni shinaide! = jangan diladeni!
• ikemen = cowok keren
• ichiyazuke = sistim kebut semalam/sks
• ki ni shinai = emang gw pikirin..
• kogyaru = anak baru gede/abg
• suki ni shiro! = terserah elo deh!
• kimochi= perasaan
• kekkai= pelindung
• mahcigai desu ga?= apakah aku salah
• hikaru nara= jika bercahaya
• hitorigoto= bicara sendiri
• akirameru= menyerah
• akirame nai= jangan menyerah
• mukuwareru= terbalas
• mukuwarenai= tidak terbalas
• itai= sakit
• kowai= menakutkan, serem, takut
• aniki= abang
• onichan= kakak laki2
• onechan= kakak perempuan
• imouto= adik
• tomodachi= teman
lah

*kata ganti*
saya = watashi, watakushi, shousa, boku, atashi, ore
kami = watashitachi, bokutachi, bokura, atashitachi, oretachi
kamu = anata, kimi, omae
kamu sekalian = anatagata, kimitachi, omaera
dia (laki) = kare, karera (jamak)
dia (perempuan) = kanojo, kanojora (jamak)
ini = kore, korera (jamak)
itu = sore, are, sorera (jamak), arera (jamak)

greeting
selamat = omedetou (gozaimasu)
selamat ulang tahun = tanjoubi omedetou
selamat pagi = ohayou (gozaimasu)
selamat siang = konnichiwa
selamat malam = konbanwa
selamat datang = youkoso, itteirasai
selamat tinggal = sayonara
selamat istirahat = oyasumi (nasai)
apa kabar = ogenki desuka, o kigen ikaga desuka (formal)
sampai jumpa lagi = mata aimashou, itte mairimasu

spada = gomen kudasai
permisi = shitsureishimasu
silakan = douzo
maaf = sumimasen, gomen (nasai)
terimakasih = doumo, arigatou (gozaimasu)
terimakasih kembali = dou itashimashite
iya = hai
tidak = iie
saya berangkat = ittekimasu
selamat jalan = itterasshai
saya pulang = tadaima
selamat datang = okaeri (nasai)
selamat makan = itadakimasu
terimakasih utk hidangannya = gochisousama deshita

angka (bango)
1 = ichi
2 = ni
3 = san
4 = shi/ yon
5 = go
6 = roku
7 = sichi/ nana
8 = hachi
9 = ku/ kyuu
10 = juu
11 = juuichi
12 = juuni
13 = juusan
14 = juushi/ juuyon
15 = juugo
16 = juuoku
17 = juusichi/ juunana
18 = juuhachi
19 = juukyuu
20 = nijuu
21 = nijuuichi
22 = nijuuni
23 = nijuusan
30 = sanjuu
37 = sanjuunana
40 = shijuu
50 = gojuu
60 = rokujuu
70 = nanajuu
80 = hachijuu
90 = kujuu
100 = hyaku
101 = hyakuichi
110 = hyakujuu
172 = hyakunanajuuni
1.000 = sen
1997 = sen.kyuuhyaku.kyuujuu.nana
2.000 = nisen
10.000 = man/ ichiman
1.000.000 = hyakuman

*hari-hari*
kanji:
曜日: youbi
日:nichi

minggu = nichiyoubi 日曜日
senin = getsuyoubi 月曜日
selasa = kayoubi 火曜日
rabu = suiyoubi 水曜日
kamis = mokuyoubi 木曜日
jumat = kinyoubi 金曜日
sabtu = doyoubi 土曜日

*copas/share* izin :v

pagi = asa
menjelang siang = gozen
siang = hiru
menjelang sore = gogo
sore = yuugata
malam = yoru/ ban

2 hari lalu = ototoi
kemarin = kinou
hari ini = kyou
besok = ashita
2 hari lagi = asatte
dulu = mukashi
sekarang = ima
masa depan = mirai/ shorai

minggu/ pekan = shuu
minggu depan = rai shuu

tanggal
tanggal 1 = tsuitachi
tanggal 2 = futsuka
tanggal 3 = mikka
tanggal 4 =yokka
tanggal 5 = itsuka
tanggal 6 = muika
tanggal 7 = nonoka
tanggal 8 = youka
tanggal 9 = kokonoka
tanggal 10 = toka
tanggal 11 = juuichi nichi
tanggal 12 = juuni ichi
tanggal 14 = juuyokka
tanggal 19 = juukyuu nichi
tanggal 20 = hatsuka
tanggal 21 = nijuuichi nichi
tanggal 23 = nijuusan nichi
tanggal 24 = nijuuyokka
tanggal 30 = sanjuu nichi
tanggal 31 = sanjuuichi nichi

nama bulan .:rumus: bilangan pokok + gatsu:.
januari = ichigatsu
februari = nigatsu
maret = sangatsu
april = yongatsu/ shigatsu
mei = gogatsu
juni = rokugatsu
juli = sichigatsu/ nanagatsu
agustus = hachigatsu
september = kugatsu
oktober = juugatsu
november = juuichigatsu
desember = juunigatsu

bulan = getsu
bulan lalu = sengetsu
bulan ini = kongetsu
bulan depan = raigetsu

*musim (kisetsu)*
musim panas = natsu
musim gugur = aki
musim dingin = fuyu
musim semi = haru

empat musim = shiki

tahun = nen/ toshi
tahu
kiri = hidari
di depan = mae ni
di belakang = ushiro ni
di samping = tonari ni

*anggota tubuh*
rambut = kami (no ke)
kepala = atama
mata = me
hidung = hana
telinga = mimi
gigi = ha
mulut = kuchi
tenggorokan = nodo
dada = mune
perut = onaka, hara
pusar = heso
lengan = ude
tangan = te
jari = yubi
kaki = ashi
kuku = tsume

warna
hitam = kuro
putih = shiro
merah = akai
biru = aoi
hijau = midori
kuning = soiro
ungu = murasaki
abu-abu = haiiro
jingga = orenjiiro
pink = momoiroya iy lah kata ganti
saya = watashi, watakushi, shousa, boku, atashi, ore
kami = watashitachi, bokutachi, bokura, atashitachi, oretachi
kamu = anata, kimi, omae
kamu sekalian = anatagata, kimitachi, omaera
dia (laki) = kare, karera (jamak)
dia (perempuan) = kanojo, kanojora (jamak)
ini = kore, korera (jamak)
itu = sore, are, sorera (jamak), arera (jamak)

greeting
selamat = omedetou (gozaimasu).
ohayou gozaimasu (おはようございます) = selamat pagi (pukul 06:00 – 10:30)
konnichiwa (こんにちは) = selamat siang (pukul 10:30 – 17:00)
konbanwa (こんばんは) = selamat malam (pukul 17:00 – 22:00)
oyasuminasai (おやすみなさい) = selamat tidur (biasanyadiucapkan kepada pasangan/kekasih)
sayounara (さようなら) = selamat tinggal (diucapkan sebagai salam perpisahan dalam jangka waktu yang lama)
mata ashita (またあした) = sampai jumpa besok (diucapkan apabila besok bertemu kembali)
mata raishuu (またらいしゅう) = sampai jumpa minggu depan
mata raigetsu (またらいげつ) = sampai jumpa bulan depan
mata rainen (またらいねん) = sampai jumpa tahun depan (biasanya ketika tahun baru)

1. 大きい(おおきい) ooki-i = besar
2. 小さい(ちいさい) chiisa-i = kecil
3. 長い(ながい) naga-i = panjang
4. 短い(みじかい) mijika-i = pendek
5. 多い(おおい) oo-i = banyak
6. 少ない(すくない) sukuna-i = sedikit
7. 太い(ふとい) futo-i = gemuk, tebal
8. 細い(ほそい) hoso-i = ramping, tipis
9. 厚い(あつい) atsu-i = tebal
10. 薄い(うすい) usu-i = tipis
11. 固い(かたい) kata-i = keras
12. 柔かい(やわらかい) yawaraka-i = lunak
13. 細かい(こまかい) komaka-i = kecil(uang)
14. 粗い(あらい) ara-i = kasar
15. 新しい(あたらしい) atarashi-i = baru
16. 古い(ふるい) furu-i = lama, tua
17. 高い(たかい) taka-i = mahal
18. 安い(やすい) yasu-i = murah
19. 早い(はやい) haya-i = cepat (waktu)
20. 速い(はやい) haya-i = cepat (kelajuan)
21. 遅い(おそい) oso-i = lambat
22. 遠い(とおい) too-i = jauh
23. 近い(ちかい) chika-i = dekat
24. 強い(つよい) tsuyo-i = kuat
25. 弱い(よわい) yowa-i = lemah
26. 高い(たかい) taka-i = tinggi, mahal
27. 低い(ひくい) hiku-i = rendah
28. 熱い(あつい) atsu-i = panas (utk benda seperti makanan, minuman, air, dll)
29. 冷たい(つめたい) tsumeta-i = dingin (utk benda seperti makanan, minuman, air, dll)
30. 温かい(あたたかい) atataka-i = hangat (utk benda seperti makanan, minuman, air, dll)
31. ぬるい nuru-i = kurang panas. tidak panas dan tidak dingin juga. (air)
32. 青い(あおい) ao-i = biru
33. 赤い(あかい) aka-i = merah
34. 黄色い(きいろい) kiiro-i = kuning
35. 黒い(くろい) kuro-i = hitam
36. 白い(しろい) shiro-i = putih
37. 茶色い(ちゃいろい) chairo-i = coklat
38. 丸い(まるい) maru-i = bundar, bulat
39. 甘い(あまい) ama-i = manis
40. 辛い(からい) kara-i = pedas
41. すっぱい suppa-i = asam
42. 塩辛い(しおからい) shiokara-i = asin
43. 苦い(にがい) niga-i = pahit
44. 濃い(こい) ko-i = pekat
45. 薄い(うすい) usu-i = tipis, encer(rasanya)
46. おいしい oishi-i = enak
47. まずい mazu-i = tidak enak
48. 暑い(あつい) atsu-i = panas(suhu)
49. 寒い(さむい) samu-i = dingin(suhu)
50. 暖かい(あたたかい) atataka-i = hangat(suhu)
51. 涼しい(すずしい) suzushi-i = sejuk(suhu)
52. 蒸暑い(むしあつい) mushiatsu-i = panas gerah(suhu)
53. 明るい(あかるい) akaru-i = terang, riang
54. 暗い(くらい) kura-i = gelap, suram
55. 汚い(きたない) kitana-i = kotor
56. 重い(おもい) omo-i = berat
57. 軽い(かるい) karu-i = ringan
58. 詳しい(くわしい) kuwashi-i = detail
59. 難しい(むずかしい) muzukashi-i = sulit
60. 易しい(やさしい) yasashi-i = mudah
61. 珍しい(めずらしい) mezurashi-i = langka
62. おかしい(おかしい) okashi-i = aneh, lucu
63. 危ない(あぶない) abuna-i = berbahaya
64. うまい(うまい) uma-i = enak, pandai
65. いい(いい) i-i = bagus
66. 悪い(わるい) waru-i = jelek
67. ひどい(ひどい) hido-i = kejam
68. うるさい(うるさい) urusa-i = berisik
69. 忙しい(いそがしい) isogashi-i = sibuk
70. 正しい(ただしい) tadashi-i = benar
71. すごい sugo-i = hebat
72. 素晴らしい(すばらしい) subarashi-i = luar biasa
73. かっこいい kakkoi-i = keren, terlihat bagus
74. えらい era-i = pintar, hebat, bagus
75. 仲がいい(なかがいい) naka ga i-i = rukun, akrab (*ini bukan kosa kata tp kalimat)
76. 親しい(したしい) shitashi-i = akrab
77. 優しい(やさしい) yasashi-i = baik hati, ramah
78. かわいい(かわいい) kawai-i = cantik, lucu, imut
79. 美しい(うつくしい) utsukushi-i = indah
80. 厳しい(きびしい) kibishi-i = tegas
81. 大人しい(おとなしい) otonashi-i = bersifat lemah lembut dan tidak keras
82. 楽しい(たのしい) tanoshi-i = menyenangkan
83. 面白い(おもしろい) omoshiro-i = menarik, lucu
84. つまらない tsumarana-i = membosankan, tidak menarik
85. うれしい ureshi-i = senang, gembira
86. 寂しい(さびしい) sabishi-i = merasa sepi
87. 怖い(こわい) kowa-i = takut
88. 悲しい(かなしい) kanashi-i = sedih
89. 恥かしい(はずかしい) hazukashi-i = malu
90. 羨ましい(うらやましい) urayamashi-i = iri hati
91. 懐かしい(なつかしい) natsukashi-i = terkenang, melepaskan rindu
92. 眠い(ねむい) nemu-i = mengantuk
93. 痛い(いたい) ita-i = merasa nyeri,sakit
94. 欲しい(ほしい) hoshi-i = ingin mendapatkan
95. 無い(ない) na-i = tidak ada
1. 残念(ざんねん) zannen = menyayangkan
2. 心配(しんぱい) shinpai = khawatir
3. 不安(ふあん) fuan = cemas
4. 好き(すき) suki = suka
5. 嫌い(きらい) kirai = tidak suka・benci
6. 大好き(だいすき) daisuki = suka sekali
7. 大嫌い(だいきらい) daikirai = benci sekali
8. きれい kiree = cantik, bersih
9. にぎやか nigiyaka = ramai
10. 静か(しずか) shizuka = tenang
11. 複雑(ふくざつ) fukuzatsu = rumit
12. 簡単(かんたん) kantan = mudah
13. 便利(べんり) benri = praktis
14. 不便(ふべん) fuben = tidak praktis
15. 幸せ(しあわせ) shiawase = bahagia
16. 素敵(すてき) suteki = bagus(dan terpesona)
17. 有名(ゆうめい) yuumee = terkenal
18. 安全(あんぜん) anzen = aman
19. 危険(きけん) kiken = berbahaya
20. 色々(いろいろ) iroiro = bermacam
21. 大丈夫(だいじょうぶ) daijoobu = tidak apa apa
22. 大事(だいじ) daiji = penting
23. 大切(たいせつ) taisetsu = penting
24. 駄目(だめ) dame = tidak boleh,situasinya tidak bagus
25. 変(へん) hen = aneh
26. 無駄(むだ) muda = sia-sia
27. 急(きゅう) kyuu = mendadak
28. 上手(じょうず) joozu = pandai
29. 下手(へた) heta = tidak pandai
30. 得意(とくい) tokui = pandai, jago
31. 苦手(にがて) nigate = tidak begitu suka, tidak pandai, lemah
32. 暇(ひま) hima = senggang
33. かわいそう kawaisoo = kasihan
34. 立派(りっぱ) rippa = megah, layak dihormati
35. 大変(たいへん) taihen = berat (*hal, kasus, peristiwa, dll, bukan benda)
36. 楽(らく) raku = enteng, mudah
37. 無理(むり) muri = mustahil
38. おしゃれ oshare = modis
39. 丁寧(ていねい) teenee = sopan, halus, ramah, teliti
40. 親切(しんせつ) shinsetsu = baik hati, ramah
41. ハンサム(はんさむ) hansamu = ganteng
42. 真面目(まじめ) majime = rajin, serius, jujur
43. 不真面目(ふまじめ) fumajime = tidak serius, tidak jujur
44. 嫌(いや) iya = tidak suka / benci
45. 一所懸命(いっしょけんめい) isshokenmee / 一生懸命(いっしょうけんめい) isshookenmei = sungguh-sungguh
46. 盛ん(さかん) sakan = popular
47. 邪魔(じゃま) jama = mengganggu
48. 十分(じゅうぶん) juubun = cukup
49. 丈夫(じょうぶ) joobu = kuat
50. 適当(てきとう) tekitoo = tepat, yg sesuai
51. 特別(とくべつ) tokubetsu = khusus, spesial
52. 自由(じゆう) jiyuu = bebas
53. まっすぐ massugu = lurus
54. 熱心(ねっしん) nesshin = dng sungguh hati, dng rajin
55. 必要(ひつよう) hitsuyoo = perlu
56. 別(べつ) betsu = lain, beda
57. 不思議(ふしぎ) fushigi = ajaib
58. 豪華(ごうか) gooka = mewah
59. 同じ(おなじ) onaji = sama
60. 伝統的(でんとうてき) dentoteki = tradisional
61. 活発(かっぱつ) kappatsu = aktif
62. 誠実(せいじつ) seejitsu = tulus hati, setia
63. わがまま(わがまま) wagamama = bersifat egois
64. 頑固(がんこ) ganko = keras kepala
65. 素直(すなお) sunao = patuh, polos
66. 意地悪(いじわる) ijiwaru = bersifat tega, jahat
67. 勝ち気(かちき) kachiki = tidak mau kalah
68. 神経質(しんけいしつ)
shinkeeshitsu = bersifat sensitif, khawatir berlebihan

smoga bermanfaat:v
tuh gan buat kalian yg mau belajar bhs jepang`, m)
}

handler.command = /^(belajarjepang|learnjapan)/i

module.exports = handler
